
spring:
  aplication-name:
          practica03

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    spring:
      datasource:
        url: jdbc:h2:file:/data/demo
        spring:
          jpa:
            defer-datasource-initialization=true:
              spring:
                h2:
                  console.enabled: true